# The entry-point Worker
name = "my-app"
compatibility_date = "2024-12-01"
main = "./entry.ts"

# It has an versioned binding to the MIDDLEWARE worker
[[auxiliary_workers]]
binding = "MIDDLEWARE"
config = "middleware/wrangler.toml"
