# The middleware Worker is internal to the application and can only be accessed via service binding.
# In this case, from the entry-point worker.
name = "my-app-middleware"
compatibility_date = "2024-12-01"
main = "./index.ts"
workers_dev = false

[[services]]
binding = "ORIGIN"
service = "my-app-ssr"