# The middleware Worker is internal to the application and can only be accessed via service binding.
# In this case, from the entry-point worker.
name = "my-app-middleware"        # Maybe doesn't strictly need a name?
compatibility_date = "2024-12-01"
main = "./index.ts"

# It has an versioned binding to the SSR worker
[[auxiliary_workers]]
binding = "SSR"
config = "../ssr/wrangler.toml"
